# Generated by Django 4.2.5 on 2023-10-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('variant', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
